#!/bin/bash

docker exec -i -t perl6magento2_web_1 /bin/bash -c "cd /var/www/html; /usr/local/bin/install-magento; /usr/local/bin/install-sampledata";
docker exec -i -t perl6magento2_web_1 /bin/bash -c "cd /var/www/html; ./bin/magento setup:di:compile";
docker exec -i -t perl6magento2_db_1 /bin/bash -c "CUSTOMERSQL=CUSTOMERSQL; echo \"$CUSTOMERSQL\" > /tmp/customer.sql; mysql -u root -pmyrootpassword -h db magento  < /tmp/customer.sql" -e CUSTOMERSQL=$(cat sql/customer-entity.sql);
